Add module name to missing assignment (#156)
* Add module name to missing assignment

This commit adds the qualified module name to assignement that are
imported from a separate modules.

The motivation for this is that currently this will cause a NameError.
For example, if we have types defined in a Python module named
demo_types, the variant assignement generated by bindgen will be:
```python
from ..imports import demo_types
variant = RuntimeValueString(list)
```
Which will generate the following error:
```console
Traceback (most recent call last):
  File "/wasmtime-py/demo-module/demo.py", line 12, in <module>
    main()
  File "wasmtime-py/demo-module/demo.py", line 8, in main
    ret = wit.something(store)
          ^^^^^^^^^^^^^^^^^^^^
  File "wasmtime-py/demo-module/dist/exports/wit.py", line 27,
  in something
    variant = RuntimeValueString(list)
              ^^^^^^^^^^^^^^^^^^
NameError: name 'RuntimeValueString' is not defined
```

With this commit, the generated assignement will instead be:
```python
from ..imports import demo_types
variant = demo_types.RuntimeValueString(list)
```

Fixes: https://github.com/bytecodealliance/wasmtime-py/issues/155
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

* Add test for external types

Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>

---------

Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>